name: Release to Update Site

on:
  push:
    branches: [main]  # Trigger the workflow on push to the master branch

jobs:
  build_release:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/vscode/devcontainers/java:0-8
    env:
      IJ_DOWNLOAD_URL: https://downloads.imagej.net/fiji/latest/fiji-linux64.tar.gz
      WIKI_USER: ${{ secrets.FIJI_SITES_USERNAME }}
      UPDATE_PASS: ${{ secrets.FIJI_SITES_PASSWORD }}
      UPDATE_SITE: evanalyzer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Docker
        run: ./build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EVAnalyzer
          path: ./bin/EVAnalyzer.jar
          retention-days: 30